name: Build and Deploy arttteo-api

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # PROD SSH KEY
      - name: Set up SSH for PROD
        if: github.ref == 'refs/heads/main'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # TEST SSH KEY
      - name: Set up SSH for TEST
        if: github.ref == 'refs/heads/test'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TEST_EC2_SSH_KEY }}

      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        env:
          PULL_TOKEN: ${{ secrets.PULL_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e
            cd /home/ubuntu/Arttteo-Web-2026-
            sudo chown -R ubuntu:ubuntu .
            git config --global --add safe.directory \$(pwd)
            git reset --hard
            git clean -fd
            git remote set-url origin https://${PULL_TOKEN}@github.com/ArttteoSoftware/Arttteo-Web-2026-.git
            git pull origin main
            sudo chown -R www-data:www-data storage bootstrap/cache || true
            sudo chmod -R 775 storage bootstrap/cache || true
            sudo docker compose up -d --build --no-deps app
            sudo docker exec arttteo-app bash -c "composer install --no-interaction --prefer-dist && php artisan migrate --force && php artisan optimize:clear"
            sudo docker ps
          EOF

      - name: Deploy TEST
        if: github.ref == 'refs/heads/test'
        env:
          PULL_TOKEN: ${{ secrets.PULL_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TEST_EC2_USER }}@${{ secrets.TEST_EC2_HOST }} << EOF
            set -e
            cd /home/ubuntu/Arttteo-Web-2026-
            sudo chown -R ubuntu:ubuntu .
            git config --global --add safe.directory \$(pwd)
            git reset --hard
            git clean -fd
            git remote set-url origin https://${PULL_TOKEN}@github.com/ArttteoSoftware/Arttteo-Web-2026-.git
            git pull origin test
            sudo chown -R www-data:www-data storage bootstrap/cache || true
            sudo chmod -R 775 storage bootstrap/cache || true
            sudo docker compose up -d --build --no-deps app
            sudo docker exec arttteo-app bash -c "composer install --no-interaction --prefer-dist && php artisan migrate --force && php artisan optimize:clear"
            sudo docker ps
          EOF
